# Generated by Django 5.0.4 on 2024-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_status_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
