# Generated by Django 5.0.4 on 2024-05-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comment_options_comment_level_comment_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='main_categories',
        ),
    ]
